const KEY='siga30_portal_users_v2';
const defaultUsers=[
 {id:'u-admin',nome:'Marco',usuario:'marco',senha:'01022005',filial:'CDD',funcao:'Autor / Administrador',admin:true,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:true,desempenho:true}},
 {id:'u-joao',nome:'João Silva',usuario:'joao',senha:'1234',filial:'CDD',funcao:'Operador',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:false,desempenho:true}},
 {id:'u-ana',nome:'Ana Souza',usuario:'ana',senha:'1234',filial:'CDD',funcao:'Conferente',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:false,atividades:true,conferencias:true,desempenho:true}},
 {id:'u-carlos',nome:'Carlos Lima',usuario:'carlos',senha:'1234',filial:'CDD',funcao:'Operador + Conferente',admin:false,ativo:true,permissoes:{separacoes:true,carregamentos:true,atividades:true,conferencias:true,desempenho:true}}
];
const SESSION_KEY='siga30_session_v3';
let users=loadUsers(), currentUser=null, page='home';
const icons={
 home:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5M9 20v-5.5h6V20"/></svg>`,
 separacoes:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h10"/><circle cx="18" cy="18" r="2.5"/></svg>`,
 carregamentos:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 7h11v10H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></svg>`,
 conferencias:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/><circle cx="12" cy="12" r="9"/></svg>`,
 atividades:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>`,
 desempenho:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 19V10M12 19V5M19 19v-8"/><path d="M3 19h18"/></svg>`,
 usuarios:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3.5 19c.7-3.1 2.5-4.7 5.5-4.7s4.8 1.6 5.5 4.7"/><path d="M16 11h5M18.5 8.5v5"/></svg>`,
 perfil:`<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.5 3.1-5.2 7-5.2s6.2 1.7 7 5.2"/></svg>`,
 sair:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 5H5v14h5M14 8l4 4-4 4M9 12h9"/></svg>`
};
const navs=[['home','home','Início','always'],['separacoes','separacoes','Minhas Separações','separacoes'],['carregamentos','carregamentos','Meus Carregamentos','carregamentos'],['conferencias','conferencias','Minhas Conferências','conferencias'],['atividades','atividades','Minhas Atividades','atividades'],['desempenho','desempenho','Meu Desempenho','desempenho'],['usuarios','usuarios','Cadastrar Usuários','admin'],['perfil','perfil','Meu Perfil','always'],['sair','sair','Sair','always']];
const activities=[['08:15','09:00','Atividade','Abastecimento de endereço A-12','Finalizada','ok'],['09:02','10:05','Atividade','Organização de estoque — corredor 04','Finalizada','ok'],['10:20','11:00','Atividade','Movimentação interna — área CDD','Finalizada','ok'],['11:05','11:50','Atividade','Apoio operacional — doca 03','Finalizada','ok'],['12:15','—','Atividade','Inventário — endereço B-07','Em andamento','pending'],['13:30','14:20','Atividade','Reposição — área de separação','Finalizada','ok']];
const seps=[['LT-1025','PED-4587','Ponte Nova','860 kg','42','08:15','09:02','Finalizada','ok'],['LT-1038','PED-4621','Viçosa','620 kg','31','10:20','11:10','Em andamento','pending'],['LT-1029','PED-4601','Ubá','740 kg','38','11:45','12:30','Finalizada','ok'],['LT-1042','PED-4630','Ponte Nova','510 kg','25','14:00','—','Pendente','pending']];
const cars=[['ROM-783','Ponte Nova','João Silva','OFA-4452','12.500 kg','48','10:20','12:05','Finalizado','ok'],['ROM-781','Rio Casca','Pedro Alves','HKG-7810','7.400 kg','28','09:10','11:00','Finalizado','bad'],['ROM-790','Viçosa','Carlos Lima','ABC-1234','8.200 kg','32','14:15','—','Em andamento','pending'],['ROM-792','Ubá','Ana Souza','DEF-5678','6.900 kg','27','15:00','—','Pendente','pending']];
const conf=[['Separação','PED-4587','09:10','Finalizado','—','—','—'],['Separação','LT-1025','10:45','Finalizado','—','—','—'],['Carregamento','ROM-783','12:15','Em andamento','—','—','—'],['Carregamento','ROM-785','13:30','Pendente','2','2','Volumes divergentes']];
const b=(t,c)=>`<span class="badge ${c}">${t}</span>`;
function today(){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date())}
function dt(h){return `<span class="datetime"><b>${today()}</b><small>${h}</small></span>`}
function okNok(s){return b((s==='Finalizada'||s==='OK')?'OK':'NOK',(s==='Finalizada'||s==='OK')?'ok':'bad')}
const bars=a=>a.map(x=>`<div class="barrow"><label>${x[0]}</label><div class="bar"><div class="fill ${x[3]||''}" style="width:${Math.min(100,Math.round(x[1]/x[2]*100))}%"></div></div><strong>${x[1]}</strong></div>`).join('');
function loadUsers(){try{const saved=JSON.parse(localStorage.getItem(KEY));return Array.isArray(saved)&&saved.length?saved:structuredClone(defaultUsers)}catch(e){return structuredClone(defaultUsers)}}
function saveUsers(){localStorage.setItem(KEY,JSON.stringify(users))}
function initials(n){return n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function renderNav(){if(!currentUser)return;document.querySelector('#nav').innerHTML=navs.filter(x=>x[3]==='always'||x[3]==='admin'&&currentUser.admin||currentUser.permissoes[x[3]]).map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')"><span class="nav-icon">${icons[x[1]]}</span><span class="nav-text">${x[2]}</span></button>`).join('')}
function updateIdentity(){const n=currentUser.nome, ini=initials(n);document.querySelector('#sideName').textContent=n;document.querySelector('#sideRole').textContent=currentUser.funcao;document.querySelector('#sideInitials').textContent=ini;document.querySelector('#headerWho').textContent=`${currentUser.filial} · ${n}`;document.querySelector('#headerInitials').textContent=ini}
function allowed(p){if(p==='usuarios')return !!currentUser?.admin;if(['home','perfil','sair'].includes(p))return true;return !!currentUser?.permissoes[p]}
function go(p){if(p==='sair'){logout();return}if(!allowed(p)){toast('Você não tem permissão para acessar esta tela.','bad');return}saveUiState();page=p;render();restoreUiState();document.querySelector('aside').classList.remove('open')}
function render(){if(!currentUser)return;renderNav();updateIdentity();const f={home,separacoes,carregamentos,conferencias,atividades,desempenho,usuarios,perfil};document.querySelector('#main').innerHTML=(f[page]||home)()}
function home(){return `<div class="title"><h1>Olá, ${esc(currentUser.nome)}!</h1><p>Aqui está o resumo das suas atividades de hoje.</p></div><div class="cards"><div class="card c1"><small>SEPARAÇÕES</small><strong>12</strong><small>Hoje</small></div><div class="card c2"><small>CARREGAMENTOS</small><strong>8</strong><small>Hoje</small></div><div class="card c3"><small>CONFERÊNCIAS</small><strong>7</strong><small>Hoje</small></div><div class="card c4"><small>ATIVIDADES</small><strong>6</strong><small>Hoje</small></div></div><div class="two"><div class="panel"><h3>📋 Atividades feitas hoje</h3><div class="sub">Informações recebidas do SIGA original, preservando a descrição da atividade.</div>${activities.map(e=>`<div class="event"><i class="dot"></i><div><b>${e[0]} • ${e[1]}</b><small>${esc(e[2])}</small></div>${b(e[3],e[4])}</div>`).join('')}</div><div><div class="panel"><h3>📊 Atividades de hoje</h3><div class="sub">Gráfico horizontal</div>${bars([['Separações',12,12],['Carregamentos',8,12,'green'],['Conferências',7,12,'purple'],['Atividades',6,8,'dark']])}</div><div class="panel" style="margin-top:12px"><h3>📈 Resultados das operações</h3><div class="sub">OK / NOK</div>${bars([['Conferências OK',5,7,'green'],['Conferências NÃO OK',2,7,'red'],['Carregamentos OK',6,8,'green'],['Carregamentos NÃO OK',2,8,'red']])}</div></div></div>`}
function table(title,sub,h,rows){return `<div class="title"><h1>${title}</h1><p>${sub}</p></div><div class="panel"><div class="filters"><input id="tableSearch" placeholder="Pesquisar por pedido, lote, destino, motorista..." oninput="filterAll()"><select id="tableStatus" onchange="filterAll()"><option value="">Todos os status</option><option value="ok">OK / Finalizada</option><option value="pending">Em andamento</option><option value="bad">Divergência / Não OK</option></select><select id="tablePeriod" onchange="filterAll()"><option value="">Todos os períodos</option><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select><button class="btn secondary" onclick="clearFilters()">Limpar filtros</button></div><div class="tablewrap"><table class="table"><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="rows">${rows}</tbody></table></div></div>`}
function separacoes(){return table('Minhas Separações','Registro com data, hora e resultado operacional.',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Resultado'],seps.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${dt(r[5])}</td><td>${dt(r[6])}</td><td>${okNok(r[7])}</td></tr>`).join(''))}
function carregamentos(){return table('Meus Carregamentos','Registro com data, hora e resultado operacional.',['Romaneio','Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Resultado'],cars.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td>${r[5]}</td><td>${dt(r[6])}</td><td>${dt(r[7])}</td><td>${b(r[8],r[9])}</td></tr>`).join(''))}
function conferencias(){return table('Minhas Conferências','Registro com data, hora e resultado da conferência.',['Operação','Lote/Pedido','Data e hora','Resultado','Divergência','Qtd.','Observação'],conf.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${dt(r[2])}</td><td>${b(r[3],r[3]==='OK'?'ok':'bad')}</td><td>${r[4]}</td><td>${r[5]}</td><td>${r[6]}</td></tr>`).join(''))}
function atividades(){return table('Minhas Atividades','Registro com início, fim e resultado operacional.',['Início','Fim','Tipo','Descrição original do SIGA','Resultado'],activities.map(r=>`<tr data-status="${r[5]}"><td>${dt(r[0])}</td><td>${r[1]==='—'?'—':dt(r[1])}</td><td>${r[2]}</td><td>${esc(r[3])}</td><td>${r[5]==='pending'?b('Em andamento','pending'):okNok(r[4])}</td></tr>`).join(''))}
function desempenho(){return `<div class="title"><h1>Meu Desempenho</h1><p>Indicadores separados por tipo de operação.</p></div><div class="cards"><div class="card c1"><small>SEPARAÇÕES</small><strong>12</strong></div><div class="card c2"><small>CARREGAMENTOS</small><strong>8</strong></div><div class="card c3"><small>CONFERÊNCIAS</small><strong>7</strong></div><div class="card c4"><small>ATIVIDADES</small><strong>6</strong></div></div><div class="panel" style="margin-top:12px"><h3>Desempenho</h3>${bars([['Separações',12,15],['Carregamentos',8,10,'green'],['Conferências',7,10,'purple'],['Atividades',6,8,'dark']])}</div>`}
function usuarios(){if(!currentUser?.admin)return denied();return `<div class="title"><h1>Cadastrar Usuários</h1><p>Somente o Autor / Administrador pode criar usuários e liberar funções individualmente.</p></div><div class="panel"><h3>Novo usuário</h3><div class="sub">Acesso, função e permissões ficam vinculados ao usuário.</div><div class="user-form" style="margin-top:14px"><div class="field"><label>Nome completo</label><input id="newNome" placeholder="Ex.: João da Silva"></div><div class="field"><label>Usuário de acesso</label><input id="newUsuario" placeholder="Ex.: joao.silva"></div><div class="field"><label>Senha</label><input id="newSenha" type="password" placeholder="Crie uma senha"></div><div class="field"><label>Filial</label><select id="newFilial"><option>CDD</option></select></div><div class="field"><label>Função</label><select id="newFuncao"><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option></select></div><div class="field"><label>Status</label><select id="newAtivo"><option value="true">Ativo</option><option value="false">Bloqueado</option></select></div></div><h3 style="margin-top:18px">Permissões individuais</h3><div class="checks"><label><input id="pSep" type="checkbox" checked> Visualizar minhas separações</label><label><input id="pCar" type="checkbox" checked> Visualizar meus carregamentos</label><label><input id="pAti" type="checkbox" checked> Visualizar minhas atividades</label><label><input id="pCon" type="checkbox"> Visualizar minhas conferências</label><label><input id="pDes" type="checkbox" checked> Visualizar meu desempenho</label></div><div class="form-actions"><button class="btn" onclick="createUser()">Cadastrar usuário</button><button class="btn secondary" onclick="clearUserForm()">Limpar</button></div></div><div class="panel" style="margin-top:12px"><h3>Usuários cadastrados</h3><div class="tablewrap"><table class="table"><thead><tr><th>Nome</th><th>Usuário</th><th>Função</th><th>Filial</th><th>Permissões</th><th>Status</th><th>Ação</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.usuario)}</td><td>${esc(u.funcao)}</td><td>${esc(u.filial)}</td><td>${permSummary(u)}</td><td>${b(u.ativo?'ATIVO':'BLOQUEADO',u.ativo?'ok':'bad')}</td><td>${u.admin?'<span class="sub">Administrador</span>':`<button class="btn secondary" onclick="editUser('${u.id}')">Editar</button><button class="btn ${u.ativo?'danger':'secondary'}" onclick="toggleUser('${u.id}')">${u.ativo?'Bloquear':'Ativar'}</button>`}</td></tr>`).join('')}</tbody></table></div></div>`}
function editUser(id){if(!currentUser?.admin)return denied();const u=users.find(x=>x.id===id);if(!u||u.admin){toast('Este usuário não pode ser editado.','bad');return}const p=u.permissoes||{};document.querySelector('#main').innerHTML='<div class="title"><h1>Editar Usuário</h1><p>Atualize os dados, status e permissões do usuário.</p></div><div class="panel"><h3>Dados do usuário</h3><div class="user-form" style="margin-top:14px"><div class="field"><label>Nome completo</label><input id="editNome" value="'+esc(u.nome)+'"></div><div class="field"><label>Usuário de acesso</label><input id="editUsuario" value="'+esc(u.usuario)+'"></div><div class="field"><label>Nova senha</label><input id="editSenha" type="password" placeholder="Deixe vazio para manter"></div><div class="field"><label>Filial</label><select id="editFilial"><option>CDD</option></select></div><div class="field"><label>Função</label><select id="editFuncao"><option>Operador</option><option>Conferente</option><option>Operador + Conferente</option></select></div><div class="field"><label>Status</label><select id="editAtivo"><option value="true">Ativo</option><option value="false">Bloqueado</option></select></div></div><h3 style="margin-top:18px">Permissões individuais</h3><div class="checks"><label><input id="epSep" type="checkbox"> Visualizar minhas separações</label><label><input id="epCar" type="checkbox"> Visualizar meus carregamentos</label><label><input id="epAti" type="checkbox"> Visualizar minhas atividades</label><label><input id="epCon" type="checkbox"> Visualizar minhas conferências</label><label><input id="epDes" type="checkbox"> Visualizar meu desempenho</label></div><div class="form-actions"><button class="btn" onclick="saveEditedUser(\''+u.id+'\')">Salvar alterações</button><button class="btn secondary" onclick="go(\'usuarios\')">Cancelar</button></div></div>';document.querySelector('#editFilial').value=u.filial;document.querySelector('#editFuncao').value=u.funcao;document.querySelector('#editAtivo').value=String(u.ativo);document.querySelector('#epSep').checked=!!p.separacoes;document.querySelector('#epCar').checked=!!p.carregamentos;document.querySelector('#epAti').checked=!!p.atividades;document.querySelector('#epCon').checked=!!p.conferencias;document.querySelector('#epDes').checked=!!p.desempenho;renderNav();updateIdentity()}
function saveEditedUser(id){if(!currentUser?.admin)return denied();const u=users.find(x=>x.id===id);if(!u||u.admin)return;const nome=document.querySelector('#editNome').value.trim(),usuario=document.querySelector('#editUsuario').value.trim().toLowerCase(),senha=document.querySelector('#editSenha').value;if(!nome||!usuario){toast('Nome e usuário são obrigatórios.','bad');return}if(!/^[a-z0-9._-]+$/.test(usuario)){toast('Usuário deve usar apenas letras, números, ponto, _ ou -.','bad');return}if(users.some(x=>x.id!==id&&x.usuario===usuario)){toast('Esse usuário já existe.','bad');return}u.nome=nome;u.usuario=usuario;u.filial=document.querySelector('#editFilial').value;u.funcao=document.querySelector('#editFuncao').value;u.ativo=document.querySelector('#editAtivo').value==='true';if(senha)u.senha=senha;u.permissoes={separacoes:document.querySelector('#epSep').checked,carregamentos:document.querySelector('#epCar').checked,atividades:document.querySelector('#epAti').checked,conferencias:document.querySelector('#epCon').checked,desempenho:document.querySelector('#epDes').checked};saveUsers();go('usuarios');toast('Usuário atualizado com sucesso.','ok')}
function permSummary(u){const p=u.permissoes||{};return ['separacoes','carregamentos','atividades','conferencias','desempenho'].filter(k=>p[k]).length+'/5 liberadas'}
function createUser(){if(!currentUser?.admin)return denied();const nome=document.querySelector('#newNome').value.trim(),usuario=document.querySelector('#newUsuario').value.trim().toLowerCase(),senha=document.querySelector('#newSenha').value,filial=document.querySelector('#newFilial').value,funcao=document.querySelector('#newFuncao').value,ativo=document.querySelector('#newAtivo').value==='true';if(!nome||!usuario||!senha){toast('Preencha nome, usuário e senha.','bad');return}if(!/^[a-z0-9._-]+$/.test(usuario)){toast('Usuário deve usar apenas letras, números, ponto, _ ou -.','bad');return}if(users.some(u=>u.usuario===usuario)){toast('Esse usuário já existe.','bad');return}const u={id:'u-'+Date.now(),nome,usuario,senha,filial,funcao,admin:false,ativo,permissoes:{separacoes:document.querySelector('#pSep').checked,carregamentos:document.querySelector('#pCar').checked,atividades:document.querySelector('#pAti').checked,conferencias:document.querySelector('#pCon').checked,desempenho:document.querySelector('#pDes').checked}};users.push(u);saveUsers();clearUserForm();render();toast('Usuário cadastrado com sucesso.','ok')}
function clearUserForm(){['newNome','newUsuario','newSenha'].forEach(id=>document.querySelector('#'+id).value='');document.querySelector('#pSep').checked=true;document.querySelector('#pCar').checked=true;document.querySelector('#pAti').checked=true;document.querySelector('#pCon').checked=false;document.querySelector('#pDes').checked=true}
function toggleUser(id){if(!currentUser?.admin)return denied();const u=users.find(x=>x.id===id);if(!u)return;u.ativo=!u.ativo;saveUsers();render();toast(`${u.nome}: ${u.ativo?'acesso ativado':'acesso bloqueado'}.`,'ok')}
function perfil(){return `<div class="title"><h1>Meu Perfil</h1><p>Dados do usuário conectado.</p></div><div class="profile"><div class="panel" style="text-align:center"><div class="me" style="justify-content:center"><i>${initials(currentUser.nome)}</i></div><h3>${esc(currentUser.nome)}</h3><div class="sub">${esc(currentUser.funcao)} • ${esc(currentUser.filial)}</div></div><div class="panel"><h3>Minhas permissões</h3>${[['separacoes','Visualizar minhas separações'],['carregamentos','Visualizar meus carregamentos'],['atividades','Visualizar minhas atividades'],['conferencias','Visualizar minhas conferências'],['desempenho','Visualizar meu desempenho']].map(x=>`<div class="permission">${currentUser.permissoes[x[0]]?'☑':'☐'} ${x[1]}</div>`).join('')}</div></div>`}
function denied(){return `<div class="panel"><h3>Acesso não autorizado</h3><p class="sub">Seu usuário não possui permissão para esta área.</p></div>`}
function filter(v){const input=document.querySelector('#tableSearch');if(input)input.value=v||'';filterAll()}
function filterAll(){const q=(document.querySelector('#tableSearch')?.value||'').trim().toLowerCase(),status=document.querySelector('#tableStatus')?.value||'',period=document.querySelector('#tablePeriod')?.value||'',now=new Date();document.querySelectorAll('#rows tr').forEach(row=>{const text=row.innerText.toLowerCase();let ok=true;if(q&&!text.includes(q))ok=false;if(status==='ok'&&!row.querySelector('.ok'))ok=false;if(status==='bad'&&!row.querySelector('.bad'))ok=false;if(status==='pending'&&!/em andamento/.test(text)&&!row.dataset.status?.includes('pending'))ok=false;if(period){const m=row.innerText.match(/\b(\d{2})\/(\d{2})\/(\d{4})\b/);if(!m)ok=false;else{const d=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));const diff=Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate())-new Date(d.getFullYear(),d.getMonth(),d.getDate()))/86400000);if(period==='today'&&diff!==0)ok=false;if(period==='7'&&(diff<0||diff>6))ok=false;if(period==='30'&&(diff<0||diff>29))ok=false}}row.style.display=ok?'':'none'})}
function clearFilters(){const a=document.querySelector('#tableSearch'),b=document.querySelector('#tableStatus'),c=document.querySelector('#tablePeriod');if(a)a.value='';if(b)b.value='';if(c)c.value='';filterAll()}

function login(){const usuario=document.querySelector('#u').value.trim().toLowerCase(),senha=document.querySelector('#pw').value,filial=document.querySelector('#fil').value,msg=document.querySelector('#loginmsg');const u=users.find(x=>x.usuario===usuario&&x.senha===senha&&x.filial===filial);if(!u){msg.textContent='Usuário, senha ou filial inválidos.';return}if(!u.ativo){msg.textContent='Usuário bloqueado. Procure o administrador.';return}currentUser=u;page='home';msg.textContent='';localStorage.setItem(SESSION_KEY,JSON.stringify({id:u.id,usuario:u.usuario}));localStorage.setItem(UI_STATE_KEY,JSON.stringify({page:'home',fields:{}}));document.querySelector('#login').classList.add('hide');document.querySelector('#app').classList.remove('hide');render()}
function logout(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem(UI_STATE_KEY);clearUiState();currentUser=null;page='home';document.querySelector('#app').classList.add('hide');document.querySelector('#login').classList.remove('hide');document.querySelector('#u').value='';document.querySelector('#pw').value='';document.querySelector('#loginmsg').textContent=''}
function toast(msg,type='ok'){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.appendChild(el)}el.className='toast '+type;el.textContent=msg;clearTimeout(window._toast);window._toast=setTimeout(()=>el.remove(),2600)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const UI_STATE_KEY='siga30_ui_state_v4';
function saveUiState(){try{const data={page,fields:{}};document.querySelectorAll('#main input,#main select,#main textarea').forEach(el=>{if(!el.id||el.type==='password')return;data.fields[el.id]={value:el.value,checked:!!el.checked,type:el.type}});localStorage.setItem(UI_STATE_KEY,JSON.stringify(data))}catch(e){}}
function restoreUiState(){try{const data=JSON.parse(localStorage.getItem(UI_STATE_KEY)||'null');if(!data)return;if(data.page&&allowed(data.page))page=data.page;Object.entries(data.fields||{}).forEach(([id,v])=>{const el=document.getElementById(id);if(!el)return;if(el.type==='checkbox')el.checked=!!v.checked;else el.value=v.value})}catch(e){}}
function clearUiState(){localStorage.removeItem(UI_STATE_KEY)}
function boot(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');if(s){const u=users.find(x=>x.id===s.id&&x.usuario===s.usuario);if(u&&u.ativo){currentUser=u;document.querySelector('#login').classList.add('hide');document.querySelector('#app').classList.remove('hide');const saved=JSON.parse(localStorage.getItem(UI_STATE_KEY)||'null');page=saved&&allowed(saved.page)?saved.page:'home';render();restoreUiState();return}}}catch(e){}document.querySelector('#login').classList.remove('hide');document.querySelector('#app').classList.add('hide')}
window.addEventListener('beforeunload',saveUiState);
document.addEventListener('input',e=>{if(e.target.closest('#main'))saveUiState()});
document.addEventListener('change',e=>{if(e.target.closest('#main'))saveUiState()});
boot();
