/* SIGA 3.0 - melhorias: filtros inteligentes, notificacoes, graficos e detalhes */
(function(){
  const oldGo=window.go;
  const statusKey=s=>{const v=String(s||'').toLowerCase();if(v.includes('pend'))return 'pending';if(v.includes('andamento'))return 'progress';if(v.includes('final')||v.includes('ok'))return 'final';return 'other'};
  const statusLabel=s=>{const k=statusKey(s);return k==='pending'?'Pendente':k==='progress'?'Em andamento':k==='final'?'Finalizado':String(s||'')};
  const esc2=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const dateText=()=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());
  const dateTime=h=>'<span class="datetime"><b>'+dateText()+'</b><small>'+h+'</small></span>';
  const badge=(t,k)=>'<span class="badge '+k+'">'+t+'</span>';
  const data={separacoes:window.seps||[],carregamentos:window.cars||[],conferencias:window.conf||[],atividades:window.activities||[]};
  window.table=function(title,sub,h,rows){return '<div class="title"><h1>'+title+'</h1><p>'+sub+'</p></div><div class="panel"><div class="smart-filter-head"><div><b>Filtros inteligentes</b><small>Combine busca, status, período e ordenação.</small></div><span id="filterCount" class="filter-count">0 registros</span></div><div class="filters"><input id="tableSearch" placeholder="🔎 Buscar pedido, lote, destino, motorista..." oninput="filterAll()"><select id="tableStatus" onchange="filterAll()"><option value="">Todos os status</option><option value="pending">Pendente</option><option value="progress">Em andamento</option><option value="final">Finalizado</option></select><select id="tablePeriod" onchange="filterAll()"><option value="">Todos os períodos</option><option value="today">Hoje</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option></select><select id="tableOrder" onchange="sortRows()"><option value="">Ordem original</option><option value="az">A → Z</option><option value="za">Z → A</option></select><button class="btn secondary" onclick="clearFilters()">Limpar filtros</button></div><div class="quick-filters"><button class="filter-chip active" onclick="setSmartStatus(\'\')">Todos</button><button class="filter-chip" onclick="setSmartStatus(\'pending\')">Pendente</button><button class="filter-chip" onclick="setSmartStatus(\'progress\')">Em andamento</button><button class="filter-chip" onclick="setSmartStatus(\'final\')">Finalizado</button></div><div class="tablewrap"><table class="table"><thead><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody id="rows">'+rows+'</tbody></table></div></div>'};
  window.filterAll=function(){const q=(document.querySelector('#tableSearch')?.value||'').trim().toLowerCase(),st=document.querySelector('#tableStatus')?.value||'',period=document.querySelector('#tablePeriod')?.value||'',base=new Date();let n=0;document.querySelectorAll('#rows tr').forEach(row=>{const text=(row.dataset.search||row.innerText||'').toLowerCase();let ok=!q||text.includes(q);if(st&&row.dataset.status!==st)ok=false;if(period){const m=(row.innerText||'').match(/\\b(\\d{2})\\/(\\d{2})\\/(\\d{4})\\b/);if(!m)ok=false;else{const d=new Date(+m[3],+m[2]-1,+m[1]);const diff=Math.floor((new Date(base.getFullYear(),base.getMonth(),base.getDate())-new Date(d.getFullYear(),d.getMonth(),d.getDate()))/86400000);if(period==='today'&&diff!==0)ok=false;if(period==='7'&&(diff<0||diff>6))ok=false;if(period==='30'&&(diff<0||diff>29))ok=false)}}row.style.display=ok?'':'none';if(ok)n++});const c=document.querySelector('#filterCount');if(c)c.textContent=n+' registro'+(n===1?'':'s')};
  window.setSmartStatus=function(v){const s=document.querySelector('#tableStatus');if(s)s.value=v;document.querySelectorAll('.filter-chip').forEach((x,i)=>x.classList.toggle('active',(v===''&&i===0)||x.textContent.toLowerCase().replace(' ','')===({pending:'pendente',progress:'emandamento',final:'finalizado'}[v]||'todos')));filterAll()};
  window.sortRows=function(){const tb=document.querySelector('#rows'),m=document.querySelector('#tableOrder')?.value;if(!tb||!m)return;const rs=[...tb.querySelectorAll('tr')];rs.sort((a,b)=>{const A=(a.dataset.search||a.innerText).toLowerCase(),B=(b.dataset.search||b.innerText).toLowerCase();return m==='az'?A.localeCompare(B,'pt-BR'):B.localeCompare(A,'pt-BR')});rs.forEach(x=>tb.appendChild(x));filterAll()};
  window.clearFilters=function(){['tableSearch','tableStatus','tablePeriod','tableOrder'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.querySelectorAll('.filter-chip').forEach((x,i)=>x.classList.toggle('active',i===0));filterAll()};
  function rowButton(type,i){return '<button class="btn secondary" onclick="openDetail(\\''+type+'\\','+i+')">Ver detalhes</button>'}
  window.separacoes=function(){return table('Minhas Separações','Registro com busca inteligente e consulta detalhada.',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status','Ação'],data.separacoes.map((r,i)=>'<tr data-status="'+statusKey(r[7])+'" data-search="'+esc2(r.join(' '))+'"><td><b>'+r[0]+'</b></td><td>'+r[1]+'</td><td>'+r[2]+'</td><td>'+r[3]+'</td><td>'+r[4]+'</td><td>'+dateTime(r[5])+'</td><td>'+(r[6]==='—'?'—':dateTime(r[6]))+'</td><td>'+badge(statusLabel(r[7]),statusKey(r[7]))+'</td><td>'+rowButton('separacao',i)+'</td></tr>').join(''))};
  window.carregamentos=function(){return table('Meus Carregamentos','Registro com busca inteligente e consulta detalhada.',['Romaneio','Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Status','Ação'],data.carregamentos.map((r,i)=>'<tr data-status="'+statusKey(r[8])+'" data-search="'+esc2(r.join(' '))+'"><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td><td>'+r[3]+'</td><td>'+r[4]+'</td><td>'+r[5]+'</td><td>'+dateTime(r[6])+'</td><td>'+(r[7]==='—'?'—':dateTime(r[7]))+'</td><td>'+badge(statusLabel(r[8]),statusKey(r[8]))+'</td><td>'+rowButton('carregamento',i)+'</td></tr>').join(''))};
  window.conferencias=function(){return table('Minhas Conferências','Registro com busca inteligente e consulta detalhada.',['Operação','Lote/Pedido','Data e hora','Status','Divergência','Qtd.','Observação','Ação'],data.conferencias.map((r,i)=>'<tr data-status="'+statusKey(r[3])+'" data-search="'+esc2(r.join(' '))+'"><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+dateTime(r[2])+'</td><td>'+badge(statusLabel(r[3]),statusKey(r[3]))+'</td><td>'+r[4]+'</td><td>'+r[5]+'</td><td>'+r[6]+'</td><td>'+rowButton('conferencia',i)+'</td></tr>').join(''))};
  window.atividades=function(){return table('Minhas Atividades','Registro com busca inteligente e consulta detalhada.',['Início','Fim','Tipo','Descrição','Status','Ação'],data.atividades.map((r,i)=>'<tr data-status="'+statusKey(r[4])+'" data-search="'+esc2(r.join(' '))+'"><td>'+dateTime(r[0])+'</td><td>'+(r[1]==='—'?'—':dateTime(r[1]))+'</td><td>'+r[2]+'</td><td>'+esc2(r[3])+'</td><td>'+badge(statusLabel(r[4]),statusKey(r[4]))+'</td><td>'+rowButton('atividade',i)+'</td></tr>').join(''))};
  window.openDetail=function(type,index){window._sigaDetail={type,index};window.page='detalhe';window.render()};
  window.detalhe=function(){const d=window._sigaDetail||{},r=data[d.type]?.[d.index];if(!r)return '<div class="panel"><h3>Detalhe não encontrado</h3></div>';const map={separacao:['Detalhes da Separação',['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status']],carregamento:['Detalhes do Carregamento',['Romaneio','Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Status']],conferencia:['Detalhes da Conferência',['Operação','Lote/Pedido','Data e hora','Status','Divergência','Qtd.','Observação']],atividade:['Detalhes da Atividade',['Início','Fim','Tipo','Descrição','Status']]},m=map[d.type],vals=r.slice();if(d.type==='separacao'){vals[5]=dateTime(r[5]);vals[6]=r[6]==='—'?'—':dateTime(r[6])}if(d.type==='carregamento'){vals[6]=dateTime(r[6]);vals[7]=r[7]==='—'?'—':dateTime(r[7])}if(d.type==='conferencia')vals[2]=dateTime(r[2]);if(d.type==='atividade'){vals[0]=dateTime(r[0]);vals[1]=r[1]==='—'?'—':dateTime(r[1])}return '<div class="title"><h1>'+m[0]+'</h1><p>Consulta completa do registro selecionado.</p></div><div class="panel"><div class="detail-grid">'+m[1].map((x,i)=>'<div class="detail-card"><small>'+x+'</small><b>'+(x==='Status'?badge(statusLabel(r[i]),statusKey(r[i])):vals[i])+'</b></div>').join('')+'</div><div class="form-actions"><button class="btn secondary" onclick="go(\\''+(d.type==='separacao'?'separacoes':d.type==='carregamento'?'carregamentos':d.type==='conferencia'?'conferencias':'atividades')+'\\')">← Voltar para lista</button></div></div>'};
  window.notificacoes=function(){const items=[['pending','!','Operação em andamento','A separação LT-1038 está em andamento.','separacao',1],['ok','✓','Conferência finalizada','A conferência PED-4587 foi finalizada.','conferencia',0],['bad','!','Divergência registrada','O romaneio ROM-785 possui volumes divergentes.','conferencia',3],['pending','!','Atividade em andamento','O inventário do endereço B-07 continua em andamento.','atividade',4]];return '<div class="title"><h1>Central de Notificações</h1><p>Alertas, pendências e atualizações importantes das suas operações.</p></div><div class="panel"><div class="notification-summary"><div><b>'+items.length+'</b><small>Total</small></div><div><b>'+items.filter(x=>x[0]==='pending').length+'</b><small>Em acompanhamento</small></div><div><b>'+items.filter(x=>x[0]==='bad').length+'</b><small>Alertas</small></div></div><div class="notification-list">'+items.map(x=>'<div class="notification-item"><div class="notification-icon '+x[0]+'">'+x[1]+'</div><div><b>'+x[2]+'</b><p>'+x[3]+'</p><small>Hoje</small></div><button class="btn secondary" onclick="openDetail(\\''+x[4]+'\\','+x[5]+')">Ver detalhes</button></div>').join('')+'</div></div>'};
  const originalHome=window.home;
  window.home=function(){const h=originalHome();return h.replace('<div class="two">','<div class="panel professional-dashboard" style="margin-top:12px"><div class="smart-filter-head"><div><b>Visão profissional</b><small>Resumo visual das operações e seus status.</small></div><button class="btn secondary" onclick="go(\'notificacoes\')">🔔 Notificações</button></div><div class="pro-chart"><div class="pro-ring"><span><b>82%</b><small>Concluído</small></span></div><div class="pro-legend"><div><i class="ok"></i>Finalizado <b>18</b></div><div><i class="pending"></i>Em andamento <b>3</b></div><div><i class="bad"></i>Pendente <b>3</b></div></div></div></div><div class="two">')};
  const originalRender=window.render;
  window.render=function(){if(!window.currentUser&&typeof currentUser==='undefined')return;const f={home:window.home,separacoes:window.separacoes,carregamentos:window.carregamentos,conferencias:window.conferencias,atividades:window.atividades,desempenho:window.desempenho,notificacoes:window.notificacoes,usuarios:window.usuarios,perfil:window.perfil,detalhe:window.detalhe};if(typeof renderNav==='function')renderNav();if(typeof updateIdentity==='function')updateIdentity();document.querySelector('#main').innerHTML=(f[window.page]||window.home)();if(window.page!=='home'&&window.page!=='detalhe')filterAll()};
  const oldGoFn=window.go;window.go=function(p){if(p==='detalhe'||p==='notificacoes'){window.page=p;window.render();document.querySelector('aside')?.classList.remove('open');return}return oldGoFn(p)};
})();