/* SIGA 3.0 - recursos complementares */
(function(){
const statusKey=s=>{const v=String(s||'').toLowerCase();if(v.includes('pend'))return'pending';if(v.includes('andamento'))return'progress';if(v.includes('final')||v.includes('ok'))return'final';return'other'};
const statusLabel=s=>{const k=statusKey(s);return k==='pending'?'Pendente':k==='progress'?'Em andamento':k==='final'?'Finalizado':String(s||'')};
const esc2=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const dt2=h=>'<span class="datetime"><b>'+new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date())+'</b><small>'+h+'</small></span>';
const badge=(t,k)=>'<span class="badge '+k+'">'+t+'</span>';
window.filterAll=function(){const q=(document.querySelector('#tableSearch')?.value||'').trim().toLowerCase(),st=document.querySelector('#tableStatus')?.value||'',period=document.querySelector('#tablePeriod')?.value||'',now=new Date();let n=0;document.querySelectorAll('#rows tr').forEach(row=>{const text=(row.dataset.search||row.innerText||'').toLowerCase();let ok=!q||text.includes(q);if(st&&row.dataset.status!==st)ok=false;if(period){const m=(row.innerText||'').match(/\\b(\\d{2})\\/(\\d{2})\\/(\\d{4})\\b/);if(!m)ok=false;else{const d=new Date(+m[3],+m[2]-1,+m[1]),base=new Date(now.getFullYear(),now.getMonth(),now.getDate()),diff=Math.floor((base-d)/86400000);if(period==='today'&&diff!==0)ok=false;if(period==='7'&&(diff<0||diff>6))ok=false;if(period==='30'&&(diff<0||diff>29))ok=false}}row.style.display=ok?'':'none';if(ok)n++});const c=document.querySelector('#filterCount');if(c)c.textContent=n+' registro'+(n===1?'':'s')};
window.setSmartStatus=function(v){const s=document.querySelector('#tableStatus');if(s)s.value=v;filterAll()};
window.sortRows=function(){const tb=document.querySelector('#rows'),m=document.querySelector('#tableOrder')?.value;if(!tb||!m)return;const rs=[...tb.querySelectorAll('tr')];rs.sort((a,b)=>{const A=(a.dataset.search||a.innerText).toLowerCase(),B=(b.dataset.search||b.innerText).toLowerCase();return m==='az'?A.localeCompare(B,'pt-BR'):B.localeCompare(A,'pt-BR')});rs.forEach(x=>tb.appendChild(x));filterAll()};
window.clearFilters=function(){['tableSearch','tableStatus','tablePeriod','tableOrder'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});filterAll()};
const detailMap={separacao:{title:'Detalhes da Separação',back:'separacoes',data:()=>seps},carregamento:{title:'Detalhes do Carregamento',back:'carregamentos',data:()=>cars},conferencia:{title:'Detalhes da Conferência',back:'conferencias',data:()=>conf},atividade:{title:'Detalhes da Atividade',back:'atividades',data:()=>activities}};
window.openDetail=function(type,index){const d=detailMap[type],r=d?.data()?.[index];if(!r)return;document.querySelector('#main').innerHTML=detailHTML(type,index);document.querySelector('aside')?.classList.remove('open')};
function detailHTML(type,index){const d=detailMap[type],r=d.data()[index],labels=type==='separacao'?['Lote','Pedido','Destino','Peso','Volumes','Início','Fim','Status']:type==='carregamento'?['Romaneio','Destino','Motorista','Placa','Peso','Volumes','Início','Fim','Status']:type==='conferencia'?['Operação','Lote/Pedido','Data e hora','Status','Divergência','Qtd.','Observação']:['Início','Fim','Tipo','Descrição','Status'];const vals=r.slice();if(type==='separacao'){vals[5]=dt2(r[5]);vals[6]=r[6]==='—'?'—':dt2(r[6])}if(type==='carregamento'){vals[6]=dt2(r[6]);vals[7]=r[7]==='—'?'—':dt2(r[7])}if(type==='conferencia')vals[2]=dt2(r[2]);if(type==='atividade'){vals[0]=dt2(r[0]);vals[1]=r[1]==='—'?'—':dt2(r[1])}return '<div class="title"><h1>'+d.title+'</h1><p>Consulta completa do registro selecionado.</p></div><div class="panel"><div class="detail-grid">'+labels.map((x,i)=>'<div class="detail-card"><small>'+x+'</small><b>'+(x==='Status'?badge(statusLabel(r[i]),statusKey(r[i])):vals[i])+'</b></div>').join('')+'</div><div class="form-actions"><button class="btn secondary" onclick="go(\\''+d.back+'\\')">← Voltar para lista</button></div></div>'}
window.notificacoes=function(){const items=[['pending','!','Operação em andamento','A separação LT-1038 está em andamento.','separacao',1],['ok','✓','Conferência finalizada','A conferência PED-4587 foi finalizada.','conferencia',0],['bad','!','Divergência registrada','O romaneio ROM-785 possui volumes divergentes.','conferencia',3],['pending','!','Atividade em andamento','O inventário B-07 continua em andamento.','atividade',4]];return '<div class="title"><h1>Central de Notificações</h1><p>Alertas, pendências e atualizações importantes.</p></div><div class="panel"><div class="notification-summary"><div><b>'+items.length+'</b><small>Total</small></div><div><b>'+items.filter(x=>x[0]==='pending').length+'</b><small>Em acompanhamento</small></div><div><b>'+items.filter(x=>x[0]==='bad').length+'</b><small>Alertas</small></div></div><div class="notification-list">'+items.map(x=>'<div class="notification-item"><div class="notification-icon '+x[0]+'">'+x[1]+'</div><div><b>'+x[2]+'</b><p>'+x[3]+'</p><small>Hoje</small></div><button class="btn secondary" onclick="openDetail(\\''+x[4]+'\\','+x[5]+')">Ver detalhes</button></div>').join('')+'</div></div>'};
const originalGo=window.go;window.go=function(p){if(p==='notificacoes'){document.querySelector('#main').innerHTML=notificacoes();document.querySelector('aside')?.classList.remove('open');return}return originalGo(p)};
window.openDetail=openDetail;
window.addEventListener('load',()=>{setTimeout(()=>{const main=document.querySelector('#main');if(!main)return;const home=main.querySelector('.cards');if(home&&!main.querySelector('.professional-dashboard')){const panel=document.createElement('div');panel.className='panel professional-dashboard';panel.innerHTML='<div class="smart-filter-head"><div><b>Visão profissional</b><small>Resumo visual das operações e seus status.</small></div><button class="btn secondary" onclick="go(\\'notificacoes\\')">🔔 Notificações</button></div><div class="pro-chart"><div class="pro-ring"><span><b>82%</b><small>Concluído</small></span></div><div class="pro-legend"><div><i class="ok"></i>Finalizado <b>18</b></div><div><i class="pending"></i>Em andamento <b>3</b></div><div><i class="bad"></i>Pendente <b>3</b></div></div></div>';main.insertBefore(panel,home.nextElementSibling)}}},300)});
})();